<?php
/***************************************************************************
*                            Dolphin Smart Community Builder
*                              -------------------
*     begin                : Mon Mar 23 2006
*     copyright            : (C) 2007 BoonEx School
*     website              : http://www.boonex.com
* This file is part of Dolphin - Smart Community Builder
*
* Dolphin is free software; you can redistribute it and/or modify it under
* the terms of the GNU General Public License as published by the
* Free Software Foundation; either version 2 of the
* License, or  any later version.
*
* Dolphin is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY;
* without even the implied warranty of  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
* See the GNU General Public License for more details.
* You should have received a copy of the GNU General Public License along with Dolphin,
* see license.txt file; if not, write to marketing@boonex.com
***************************************************************************/

$sLangCategory = 'Modzzz Schools';

$aLangContent = array(

 	'_modzzz_school' => 'School',  	
 	'_modzzz_schools_page_title_browse_by_author_school_mates' => 'School Mates',  	
  	'_modzzz_schools_class_of' => 'class of',  	
	'_modzzz_schools_present' => 'present',  	

	'_modzzz_schools_type_public' => 'Public School',  	
	'_modzzz_schools_type_private' => 'Private School',  	
	'_modzzz_schools_type_charter' => 'Charter School',  	
	'_modzzz_schools_type_military' => 'Military School',  	
	'_modzzz_schools_other' => 'Other',  	
 
	'_modzzz_schools_level_kindergarten' => 'Kindergarten',
	'_modzzz_schools_level_elementary' => 'Elementary',
	'_modzzz_schools_level_high_school' => 'High School',
	'_modzzz_schools_level_junior_high' => 'Junior High',
	'_modzzz_schools_level_prep_school' => 'Preparatory School',
	'_modzzz_schools_level_technical_institute' => 'Technical Institute',
	'_modzzz_schools_level_community_college' => 'Community College',
	'_modzzz_schools_level_college' => 'College',
	'_modzzz_schools_level_university' => 'University',   
   
	'_modzzz_schools_form_caption_academic_staff_count' => 'Academic Staff Count',   
	'_modzzz_schools_form_caption_admin_staff_count' => 'Admin Staff Count',  
	'_modzzz_schools_form_caption_student_count' => 'Student Count',   
	'_modzzz_schools_form_caption_year_established' => 'Year Established',   
	'_modzzz_schools_form_caption_founder' => 'Founder',   
	'_modzzz_schools_caption_ethnicity' => 'Majority Ethnicity',   
	'_modzzz_schools_block_school_mates' => 'School Mates',   

	'_modzzz_schools_caption_year_entered' => 'Year Entered',   
	'_modzzz_schools_info_year_entered' => 'Eg. 2005 etc.',   

	'_modzzz_schools_err_year_entered' => 'you must input the Year Entered',   
	'_modzzz_schools_caption_year_left' => 'Year Left',   
	'_modzzz_schools_info_year_left' => 'Leave blank if you are still attending this school',   



 	'_modzzz_schools_caption_level' => 'Education Level',   
 	'_modzzz_schools_caption_type' => 'School Type',   
 	'_modzzz_schools_caption_sports' => 'Sport Teams',   
 	'_modzzz_schools_caption_clubs' => 'Extra-Curriculum Clubs',   
 	'_modzzz_schools_caption_qualifications' => 'Qualifications Offered',   
  	'_modzzz_schools_form_header_stats' => 'Statistics',   
  	'_modzzz_schools_form_header_details' => 'School Trivia',   

  	'_modzzz_schools_block_statistics' => 'Statistics',   
  	'_modzzz_schools_block_details' => 'School Trivia',   
  	'_modzzz_schools_block_contact' => 'Contact Info',   
  
	'_modzzz_schools_comments' => 'Comments',  	
	'_modzzz_schools_caption_categories' => 'Categories',  
	'_modzzz_schools_all_categories' => 'All Categories',  
	'_modzzz_schools_all_countries' => 'All Countries',  
	'_modzzz_schools_created' => 'Created',  
	'_modzzz_schools_block_search' => 'Quick Search',  
	
	'_modzzz_schools_regions_for_country' => 'States/Regions for',  
	'_modzzz_schools_block_browse_state' => 'Browse States', 
	'_modzzz_schools_block_browse_state_schools' => 'Browse Schools by State', 
	'_modzzz_schools_block_common_categories' => 'Common Categories', 
	'_modzzz_schools_block_latest_activities' => 'Latest Activities', 
	'_modzzz_schools_block_account' => 'Schools in my Area', 
	'_modzzz_schools_block_latest_comments' => 'Latest Comments', 

	'_modzzz_schools_block_browse_country' => 'Browse by Country', 
	'_modzzz_schools_page_title_local' => 'Browse Local Schools',  
	'_modzzz_schools_caption_browse_local' => 'Browse Local Schools in {0}', 
	'_modzzz_schools_menu_local' => 'Local', 
	'_modzzz_schools_block_sponsor' => 'Sponsor', 
	'_modzzz_schools_block_local' => 'More Local Schools',
  	'_modzzz_schools_block_other' => 'Other Schools by this member',
  	'_modzzz_schools_caption_sponsor_name' => 'Sponsor Name',
  	'_modzzz_schools_caption_sponsor_email' => 'Sponsor Email',
  	'_modzzz_schools_caption_sponsor_phone' => 'Sponsor Telephone',
  	'_modzzz_schools_caption_sponsor_website' => 'Sponsor Website',
  	'_modzzz_schools_caption_sponsor_fax' => 'Sponsor Fax',
   	'_modzzz_schools_form_header_sponsor' => 'Sponsor Info',
   	'_modzzz_schools_caption_browse_other' => 'Other Schools by {0}',
   
   	'_modzzz_schools_block_top_list' => 'Top Rated Schools',  
   	'_modzzz_schools_block_popular_list' => 'Popular Schools',  
	'_modzzz_schools_block_featured' => 'Recently Featured Schools',  
   	'_modzzz_schools_block_calendar' => 'Schools Calendar',  
	'_modzzz_schools_block_forum' => 'Latest Forum Posts',  
  
	'_modzzz_schools_continue' => 'Continue',  
	'_modzzz_schools_enter_your_school_name' => 'Enter your school name',  
	'_modzzz_schools_caption_state' => 'State',  
	'_modzzz_schools_form_caption_state' => 'State',  


	'_modzzz_schools_feed_make_admin' => '<a href="{profile_link}">{profile_nick}</a> is now an admin for school <a href="{entry_url}">{entry_title}</a>',  

	'_modzzz_schools_feed_remove_admin' => '<a href="{profile_link}">{profile_nick}</a> is no longer an admin for school <a href="{entry_url}">{entry_title}</a>',  

	'_modzzz_schools_feed_featured' => '<a href="{profile_link}">{profile_nick}</a> has featured school <a href="{entry_url}">{entry_title}</a>',  

	'_modzzz_schools_feed_unfeatured' => '<a href="{profile_link}">{profile_nick}</a> has un-featured school <a href="{entry_url}">{entry_title}</a>',  
 
	'_modzzz_schools_feed_delete' => '<a href="{profile_link}">{profile_nick}</a> removed school <a href="{entry_url}">{entry_title}</a>',  

	'_modzzz_schools_feed_post' => '<a href="{profile_link}">{profile_nick}</a> added new school <a href="{entry_url}">{entry_title}</a>',  

	'_modzzz_schools_feed_post_change' => '<a href="{profile_link}">{profile_nick}</a> changed school <a href="{entry_url}">{entry_title}</a>',  

	'_modzzz_schools_feed_join' => '<a href="{profile_link}">{profile_nick}</a> has become a fan of school <a href="{entry_url}">{entry_title}</a>',  

	'_modzzz_schools_feed_unjoin' => '<a href="{profile_link}">{profile_nick}</a> is no longer a fan of school <a href="{entry_url}">{entry_title}</a>',  

	'_modzzz_schools_feed_rate' => '<a href="{profile_link}">{profile_nick}</a> rated school <a href="{entry_url}">{entry_title}</a>',  

	'_modzzz_schools_feed_comment' => '<a href="{profile_link}">{profile_nick}</a> commented on school <a href="{entry_url}">{entry_title}</a>', 



    '_sbs_txt_title_modzzz_schools' => 'Schools',
    '_modzzz_schools' => 'Schools',
    '_modzzz_schools_fans' => 'students',
    '_modzzz_schools_students' => 'students',
    '_modzzz_schools_alumni' => 'alumni',
    '_modzzz_schools_student' => 'student',

    '_modzzz_schools_add' => 'add',
    '_modzzz_schools_wall_added_new' => 'added new',
    '_modzzz_schools_wall_object' => 'school',
    '_modzzz_schools_for_school' => 'for %s',
    '_modzzz_schools_school_single' => 'school',
    '_modzzz_schools_school_plural' => 'schools',
    '_modzzz_schools_user_unknown' => 'Someone',

    '_modzzz_schools_spy_post' => '<a href="{profile_link}">{profile_nick}</a> added new school <a href="{entry_url}">{entry_title}</a>',
    '_modzzz_schools_spy_post_change' => '<a href="{profile_link}">{profile_nick}</a> changed school <a href="{entry_url}">{entry_title}</a>',
    '_modzzz_schools_spy_join' => '<a href="{profile_link}">{profile_nick}</a> became a fan of school <a href="{entry_url}">{entry_title}</a>',
    '_modzzz_schools_spy_rate' => '<a href="{profile_link}">{profile_nick}</a> rated school <a href="{entry_url}">{entry_title}</a>',
    '_modzzz_schools_spy_comment' => '<a href="{profile_link}">{profile_nick}</a> commented school <a href="{entry_url}">{entry_title}</a>',

    '_modzzz_schools_sbs_change' => 'information was updated',
    '_modzzz_schools_sbs_comment' => 'new comment arrived',
    '_modzzz_schools_sbs_rate' => 'rating was updated',
    '_modzzz_schools_sbs_join' => 'new fan',

    '_modzzz_schools_tab_featured' => 'Featured',
    '_modzzz_schools_tab_recent' => 'Recent',
    '_modzzz_schools_tab_top' => 'Top',
    '_modzzz_schools_tab_popular' => 'Popular',
    '_modzzz_schools_page_title_browse' => 'Browse Schools',
 
    '_modzzz_schools_block_submenu_main' => 'Main',
    '_modzzz_schools_block_submenu_add_school' => 'Add',
    '_modzzz_schools_block_submenu_manage_schools' => 'Manage',
    '_modzzz_schools_block_submenu_pending_schools' => 'Pending Approval',
	'_modzzz_schools_label_attendance_period' => 'Attendance Period',    
	'_modzzz_schools_caption_membership_type' => 'Membership Type',    
	'_modzzz_schools_err_membership_type' => 'You must select membership type',    
	 
	'_modzzz_schools_err_graduated' => 'Select whether or not you Graduated',   
	'_modzzz_schools_caption_graduated' => 'Graduated',    
    '_modzzz_schools_yes' => 'Yes',    
    '_modzzz_schools_o' => 'No',    

    '_modzzz_schools_block_actions' => 'Actions',
    '_modzzz_schools_block_rate' => 'Rate',    
    '_modzzz_schools_block_info' => 'Info',
    '_modzzz_schools_block_desc' => 'Description',
    '_modzzz_schools_block_photo' => 'Photos',
    '_modzzz_schools_block_video' => 'Videos',
    '_modzzz_schools_block_sound' => 'Sounds',
    '_modzzz_schools_block_files' => 'Files',
    '_modzzz_schools_block_file' => 'Files',
    '_modzzz_schools_block_fans' => 'Fans',


    '_modzzz_schools_block_fans_unconfirmed' => 'Unconfirmed Fans',
    '_modzzz_schools_block_comments' => 'Comments',
    '_modzzz_schools_block_latest_featured_school' => 'Latest Featured School',
    '_modzzz_schools_block_recent' => 'Recent Schools',
    '_modzzz_schools_block_administration_owner' => 'Administration',
    '_modzzz_schools_block_users_schools' => 'User\'s Schools',
    '_modzzz_schools_block_my_schools' => 'My Schools',
	'_modzzz_schools_block_my_schools_joined' => 'Schools I am fan of',
    '_modzzz_schools_block_homepage' => 'Schools',

    '_modzzz_schools_caption_add' => 'Add School',
    '_modzzz_schools_caption_share_school' => 'Share School',
    '_modzzz_schools_caption_admin_actions' => 'Links',
    '_modzzz_schools_caption_pending_approval' => 'Pending Approval Schools', 
    '_modzzz_schools_caption_manage_fans' => 'Manage Fans',
  
    '_modzzz_schools_menu_root' => 'Schools',
    '_modzzz_schools_menu_main' => 'Schools Home',
    '_modzzz_schools_menu_recent' => 'Recent',
    '_modzzz_schools_menu_top_rated' => 'Top Rated',
    '_modzzz_schools_menu_popular' => 'Popular',
    '_modzzz_schools_menu_featured' => 'Featured',
    '_modzzz_schools_menu_tags' => 'Tags',
    '_modzzz_schools_menu_categories' => 'Categories',
    '_modzzz_schools_menu_calendar' => 'Calendar',
    '_modzzz_schools_menu_search' => 'Search',
    '_modzzz_schools_menu_view_school' => 'Main',
    '_modzzz_schools_menu_view_forum' => 'Forum',
    '_modzzz_schools_menu_view_comments' => 'Comments',
    '_modzzz_schools_menu_view_fans' => 'Fans', 
    '_modzzz_schools_menu_view_photos' => 'Photos',
    '_modzzz_schools_menu_view_videos' => 'Videos',
    '_modzzz_schools_menu_view_sounds' => 'Sounds',
    '_modzzz_schools_menu_view_files' => 'Files',
    '_modzzz_schools_menu_my_schools_profile' => 'Schools',

    '_modzzz_schools_menu_admin_pending_approval' => 'Pending Approval',
    '_modzzz_schools_menu_admin_entries' => 'Admin Schools',
    '_modzzz_schools_menu_admin_add_entry' => 'Add School',
    '_modzzz_schools_menu_admin_settings' => 'Settings',
    
    '_modzzz_schools_page_title_home' => 'Schools Home',
    '_modzzz_schools_page_title_calendar' => 'Schools Calendar ',
    '_modzzz_schools_page_title_comments' => 'Comments',
    '_modzzz_schools_page_title_photos' => 'Photos',
    '_modzzz_schools_page_title_videos' => 'Videos',
    '_modzzz_schools_page_title_sounds' => 'Sounds',
    '_modzzz_schools_page_title_files' => 'Files',
    '_modzzz_schools_page_title_fans' => 'School\'s Fans',
    '_modzzz_schools_page_title_students' => 'School\'s Students',
    '_modzzz_schools_page_title_alumni' => 'School\'s Alumni',


    '_modzzz_schools_page_title_my_schools' => 'My Schools',
    '_modzzz_schools_page_title_search' => 'Schools Search',
    '_modzzz_schools_page_title_add' => 'Add School', 
    '_modzzz_schools_page_title_edit' => 'Edit School',
    '_modzzz_schools_page_title_administration' => 'Schools Administration',
    '_modzzz_schools_page_title_browse' => 'Browse Schools',
    '_modzzz_schools_page_title_pending_approval' => 'Pending Approval Schools',
    '_modzzz_schools_page_title_search_results' => 'Schools Search Results',
    '_modzzz_schools_page_title_browse_by_author' => '\'s schools',
    '_modzzz_schools_page_title_browse_by_author_joined_schools' => '\'s joined schools',
    '_modzzz_schools_page_title_admin_schools' => 'Admin Schools',
    '_modzzz_schools_page_title_browse_by_category' => 'Browse Schools By Category: ',
    '_modzzz_schools_page_title_browse_by_tag' => 'Browse Schools By Tag: ',
    '_modzzz_schools_page_title_browse_recent' => 'Recent Schools',
    '_modzzz_schools_page_title_browse_top_rated' => 'Top Rated Schools',
    '_modzzz_schools_page_title_browse_popular' => 'Popular Schools',
    '_modzzz_schools_page_title_browse_featured' => 'Featured Schools',
    '_modzzz_schools_page_title_browse_by_day' => 'Browse Schools By Day: ',
    '_modzzz_schools_page_title_tags' => 'Schools Tags',
    '_modzzz_schools_page_title_categories' => 'Schools Categories',
    '_modzzz_schools_page_title_broadcast' => 'Send broadcast message to all students of this school',
    '_modzzz_schools_page_title_upload_photos' => 'Add Photos',
    '_modzzz_schools_page_title_upload_videos' => 'Add Videos',
    '_modzzz_schools_page_title_upload_sounds' => 'Add Sounds',
    '_modzzz_schools_page_title_upload_files' => 'Add Files',
    '_modzzz_schools_page_title_invite' => 'Send Invitation To ',

    '_modzzz_schools_msg_pending_approval' => 'this school is pending approval, please wait until it will be activated',
    '_modzzz_schools_msg_school_was_deleted' => 'School was deleted',
    '_modzzz_schools_msg_removed_from_featured' => 'School was removed from featured',
    '_modzzz_schools_msg_added_to_featured' => 'School was added to featured',
    '_modzzz_schools_msg_photo_is_pending_approval' => 'Photo is pending approval',
    '_modzzz_schools_msg_you_have_pending_approval_schools' => 'You have <a href="%s">%d pending approval schools</a>',
    '_modzzz_schools_msg_you_have_no_schools' => 'You have\'t posted any schools. <a href="%s">Click here</a> to add one.',
    '_modzzz_schools_msg_you_have_some_schools' => 'You have posted <a href="%s">%d school(s)</a>. <a href="%s">Click here</a> to add more.',
    '_modzzz_schools_msg_broadcast_message_sent' => 'Broadcast messages have been sent',
    '_modzzz_schools_msg_broadcast_no_recipients' => 'There are no students in this school yet',
    '_modzzz_schools_msg_joined_already' => 'You have already joined this school',
    '_modzzz_schools_msg_joined_request_pending' => 'You have already joined this school. Please wait while your request is processed by school admin(s).',
    '_modzzz_schools_msg_join_success' => 'You have successfully joined this school',
    '_modzzz_schools_msg_join_success_pending' => 'You have successfully joined this school. Please wait while your request is processed by school admin(s).',
	'_modzzz_schools_msg_leave_success' => 'You have successfully left this school',
    '_modzzz_schools_msg_invitation_sent' => '%d invitations have been sent',
    '_modzzz_schools_msg_no_users_to_invite' => 'There are no users in your contacts',

    '_modzzz_schools_admin_delete' => 'Delete',
    '_modzzz_schools_admin_activate' => 'Activate',
    '_modzzz_schools_admin_add_new_school' => 'Add New School',
    '_modzzz_schools_admin_schools' => 'Admin Schools',
    '_modzzz_schools_admin_settings' => 'Admin Settings',

    '_modzzz_schools_form_header_info' => 'School\'s Info',
    '_modzzz_schools_form_header_images' => 'Photos',
    '_modzzz_schools_form_header_videos' => 'Videos',
    '_modzzz_schools_form_header_sounds' => 'Sounds',
    '_modzzz_schools_form_header_files' => 'Files',
    '_modzzz_schools_form_header_privacy' => 'Privacy Settings',
    '_modzzz_schools_form_caption_title' => 'Title',
    '_modzzz_schools_form_err_title' => 'Please enter from 3 to 100 characters',
    '_modzzz_schools_form_caption_desc' => 'Description',
    '_modzzz_schools_form_err_desc' => 'Please enter at least 20 characters',
    '_modzzz_schools_form_err_tags' => 'Please enter tags',
    '_modzzz_schools_form_caption_author_id' => 'Author',
    '_modzzz_schools_form_info_author' => 'Author profile ID number',
    '_modzzz_schools_form_caption_keyword' => 'School Name',
    '_modzzz_schools_form_err_keyword' => 'Please enter from 3 to 100 characters',
    '_modzzz_schools_form_caption_street' => 'Street',
    '_modzzz_schools_form_err_street' => 'Please enter from 2 to 150 characters',
	'_modzzz_schools_form_caption_phone' => 'Telephone',
	'_modzzz_schools_form_caption_fax' => 'Fax',
    '_modzzz_schools_form_caption_website' => 'Website',
    '_modzzz_schools_form_header_contact_info' => 'Contact Info',
  
	'_modzzz_schools_qualifications_certificate_school' => 'School leaving Certificate',
	'_modzzz_schools_qualifications_certificate' => 'Certificate',
	'_modzzz_schools_qualifications_diploma' => 'Diploma',
	'_modzzz_schools_qualifications_diploma_high' => 'Diploma (High School)',
	'_modzzz_schools_qualifications_diploma_hnd' => 'Diploma (HND)',
	'_modzzz_schools_qualifications_diploma_post' => 'Diploma (Post Graduate)', 
	'_modzzz_schools_qualifications_associates_degree' => 'Associates Degree',
	'_modzzz_schools_qualifications_bachelors_degree' => 'Bachelors Degree',
	'_modzzz_schools_qualifications_masters_degree' => 'Masters Degree',
	'_modzzz_schools_qualifications_post_grad_degree' => 'Post Graduate Degree',
	'_modzzz_schools_clubs_debate' => 'Debate',
	'_modzzz_schools_clubs_drama' => 'Drama',
	'_modzzz_schools_clubs_community_service' => 'Community Service',
	'_modzzz_schools_clubs_dance' => 'Dance',
	'_modzzz_schools_clubs_art' => 'Art', 
	'_modzzz_schools_clubs_science' => 'Science',
	'_modzzz_schools_clubs_chess' => 'Chess',
	'_modzzz_schools_clubs_music' => 'Music',
	'_modzzz_schools_clubs_choir' => 'Choir', 
	 
	'_modzzz_schools_sports_football' => 'Football',
	'_modzzz_schools_sports_soccer' => 'Soccer',
	'_modzzz_schools_sports_basketball' => 'Basketball',
	'_modzzz_schools_sports_cricket' => 'Cricket',
	'_modzzz_schools_sports_table_tennis' => 'Table Tennis', 
	'_modzzz_schools_sports_lawn_tennis' => 'Lawn Tennis',
	'_modzzz_schools_sports_swimming' => 'Swimming',
	'_modzzz_schools_sports_hockey' => 'Hockey',
	'_modzzz_schools_sports_bowling' => 'Bowling', 
	'_modzzz_schools_sports_golf' => 'Golf',
	'_modzzz_schools_sports_netball' => 'Netball',
	'_modzzz_schools_sports_track_and_field' => 'Track and Field',
	'_modzzz_schools_sports_rugby' => 'Rugby',
	'_modzzz_schools_sports_volleyball' => 'Volleyball',
	'_modzzz_schools_sports_board_games' => 'Board Games', 
   
    '_modzzz_schools_form_caption_category' => 'Category',
    '_modzzz_schools_form_err_category' => 'Category is invalid',    
    '_modzzz_schools_form_caption_images_choice' => 'Choose',
    '_modzzz_schools_form_info_images_choice' => 'You can choose several images from your "Schools" category',
    '_modzzz_schools_form_caption_images_upload' => 'Upload',    
    '_modzzz_schools_form_info_images_upload' => 'Image will be placed in the "Schools" category automatically',
    '_modzzz_schools_form_caption_videos_choice' => 'Choose',
    '_modzzz_schools_form_info_videos_choice' => 'You can choose several videos from your "Schools" category',
    '_modzzz_schools_form_caption_videos_upload' => 'Upload',
    '_modzzz_schools_form_info_videos_upload' => 'Video will be placed in the "Schools" category automatically',
    '_modzzz_schools_form_caption_sounds_choice' => 'Choose',
    '_modzzz_schools_form_info_sounds_choice' => 'You can choose several sounds from your "Schools" category',
    '_modzzz_schools_form_caption_sounds_upload' => 'Upload',
    '_modzzz_schools_form_info_sounds_upload' => 'Sound will be placed in the "Schools" category automatically',
    '_modzzz_schools_form_caption_files_choice' => 'Choose',
    '_modzzz_schools_form_info_files_choice' => 'Unclick checkbox to remove file from this school',
    '_modzzz_schools_form_caption_files_upload' => 'Upload',
    '_modzzz_schools_form_info_files_upload' => 'File will be placed in the "Schools" category and set as private automatically',
    '_modzzz_schools_form_caption_file_title' => 'Title:',
    '_modzzz_schools_form_caption_file_price' => 'Price:',
    '_modzzz_schools_form_caption_file_allow_purcase_to' => 'Allow purchase to:',
    '_modzzz_schools_form_caption_thumb_choice' => 'Choose thumbnail',
    '_modzzz_schools_form_info_thumb_choice' => 'You can choose any image from your "Schools" category as school thumbnail',
    '_modzzz_schools_form_caption_broadcast_title' => 'Broadcast message title',
    '_modzzz_schools_form_err_broadcast_title' => 'Please enter from 3 to 100 characters', 
    '_modzzz_schools_form_caption_broadcast_message' => 'Broadcast message',
    '_modzzz_schools_form_err_broadcast_message' => 'Please enter at least 10 characters',
    '_modzzz_schools_form_caption_country' => 'Country',
    '_modzzz_schools_form_err_country' => 'Country is a required field',
    '_modzzz_schools_form_caption_city' => 'City',
    '_modzzz_schools_form_caption_address1' => 'Address',
    '_modzzz_schools_form_err_address1' => 'You must enter an Address',
    '_modzzz_schools_form_caption_place' => 'Place',
    '_modzzz_schools_form_err_place' => 'You must enter Place',
    '_modzzz_schools_form_header_location' => 'Location',  
    '_modzzz_schools_form_caption_event_start' => 'Event Start',
    '_modzzz_schools_form_err_event_start' => 'You must select an Start Date',
    '_modzzz_schools_form_caption_event_end' => 'Event End',
    '_modzzz_schools_form_err_event_end' => 'You must select an End Date',


	'_modzzz_schools_form_err_city' => 'Please enter from 2 to 50 characters',
    '_modzzz_schools_form_caption_zip' => 'Zip/Postal Code',
    '_modzzz_schools_form_err_zip' => 'Zip/Postal code is required',
    '_modzzz_schools_form_caption_join_confirmation' => 'Join Confirmation',
    '_modzzz_schools_form_info_join_confirmation' => 'If enabled, school admin(s) will have to confirm each member before he/she is added as a student.',
    '_modzzz_schools_form_join_confirmation_disabled' => 'Disabled',
    '_modzzz_schools_form_join_confirmation_enabled' => 'Enabled',
    '_modzzz_schools_form_err_join_confirmation' => 'Join confirmation field must be 0 or 1',

    '_modzzz_schools_action_title_edit' => 'Edit',
    '_modzzz_schools_action_title_delete' => 'Delete',
    '_modzzz_schools_action_title_share' => 'Share',
    '_modzzz_schools_action_title_broadcast' => 'Broadcast',
 	'_modzzz_schools_action_title_join' => 'Become Fan',  	
    '_modzzz_schools_action_title_i_attend' => 'I Attend(ed)', 
    '_modzzz_schools_action_title_leave' => 'Leave',
    '_modzzz_schools_action_title_invite' => 'Invite',
    '_modzzz_schools_action_add_to_featured' => 'Feature',    
    '_modzzz_schools_action_remove_from_featured' => 'Unfeature',
    '_modzzz_schools_action_add_school' => 'Add School',
    '_modzzz_schools_action_my_schools' => 'My Schools',
    '_modzzz_schools_action_manage_fans' => 'Fans',

    '_modzzz_schools_action_upload_photos' => 'Add Photos',
    '_modzzz_schools_action_upload_videos' => 'Add Videos',
    '_modzzz_schools_action_upload_sounds' => 'Add Sounds',
    '_modzzz_schools_action_upload_files' => 'Add Files',
    '_modzzz_schools_action_schools_home' => 'Schools Home',

    '_modzzz_schools_privacy_view_school' => 'View School',
    '_modzzz_schools_privacy_view_fans' => 'View Fans',
    '_modzzz_schools_privacy_comment' => 'Comment',
    '_modzzz_schools_privacy_rate' => 'Rate',
    '_modzzz_schools_privacy_join' => 'Become Fan',
    '_modzzz_schools_privacy_upload_photos' => 'Upload Photos',
    '_modzzz_schools_privacy_upload_videos' => 'Upload Videos',
    '_modzzz_schools_privacy_upload_sounds' => 'Upload Sounds',
    '_modzzz_schools_privacy_upload_files' => 'Upload Files',
    '_modzzz_schools_privacy_edit_school' => 'Edit School',
    '_modzzz_schools_privacy_post_in_forum' => 'Post In Forum',
    '_modzzz_schools_privacy_fans_only' => 'Fans Only',
    '_modzzz_schools_privacy_fans' => 'Fans',
    '_modzzz_schools_privacy_admins_only' => 'Admins Only',

    '_mma_schools_view_school' => 'schools view school', 
    '_mma_schools_browse' => 'schools browse', 
    '_mma_schools_search' => 'schools search', 
    '_mma_schools_add_school' => 'schools add school', 
    '_mma_schools_comments_delete_and_edit' => 'schools comments delete and edit', 
    '_mma_schools_edit_any_school' => 'schools edit any school', 
    '_mma_schools_delete_any_school' => 'schools delete any school', 
    '_mma_schools_mark_as_featured' => 'schools mark as featured', 
    '_mma_schools_approve_schools' => 'schools approve schools', 
    '_mma_schools_broadcast_message' => 'schools broadcast message',

    '_modzzz_schools_claim_subject' => 'Subject', 
    '_modzzz_schools_claim_subject_info' => 'Enter the Subject of your claim', 
    '_modzzz_schools_claim_text' => 'Message', 
    '_modzzz_schools_claim_text_info' => 'Enter your proof of claim here. It will be forwarded to the Administrators',  
	'_modzzz_schools_caption_make_claim' => 'Make Claim',
    '_modzzz_schools_claim_sent' => 'your claim request has been sent',
    '_modzzz_schools_claim_not_sent' => 'your claim request has not been sent',
    '_modzzz_schools_admin_assign' => 'Assign to Claimant',  
    '_modzzz_schools_menu_manage_claims' => 'Claims',  
    '_modzzz_schools_claimed_by' => 'Claimed by',  
    '_mma_schools_make_claim' => 'schools make claim', 
    '_modzzz_schools_action_title_claim' => 'Claim School',
    '_modzzz_schools_claimed_on' => 'Claimed on',  
  
    '_modzzz_schools_form_header_images' => 'Photos',

	'_modzzz_schools_instructor_site' => 'Registered Site Member',
	'_modzzz_schools_instructor_external' => 'Non-Member',
	'_modzzz_schools_form_caption_instructor_is_site_instructor' => 'Type of Instructor',
	'_modzzz_schools_form_err_instructor_is_site_instructor' => 'Select Type of Instructor',
	'_modzzz_schools_instructor_form_header_images' => 'Photos',
	'_modzzz_schools_form_instructor_invalid_instructor' => 'Instructor Name entered is not an active site member',  
	'_modzzz_schools_block_browse_site_instructors' => 'School Instructors (Site Members)', 
	'_modzzz_schools_block_browse_instructors' => 'School Instructors',
	'_modzzz_schools_page_title_instructors_add' => 'Add an Instructor for School - {0}',
	'_modzzz_schools_page_title_instructors_browse' => 'Browse Instructors for School - {0}',  
    '_modzzz_schools_action_title_add_instructors' => 'Add Instructor',
    '_modzzz_schools_page_title_instructors_edit' => 'Edit School Instructor',
    '_modzzz_schools_msg_school_instructor_was_deleted' => 'School Instructor was successfully deleted',
    '_modzzz_schools_msg_pending_instructors_approval' => 'this school instructor is pending approval, please wait until it will be activated',
    '_modzzz_schools_menu_view_instructors' => 'Instructors', 
    '_modzzz_schools_block_instructors' => 'School Instructors',
    '_modzzz_schools_form_caption_instructor_name' => 'Instructor Name', 
    '_modzzz_schools_privacy_view_instructors' => 'All View Instructor to', 
    '_modzzz_schools_form_caption_position' => 'Position',
    '_modzzz_schools_form_err_position' => 'Enter Position (eg. Senior Lecturer)',
    '_modzzz_schools_form_info_position' => 'eg. Senior Lecturer',
    '_modzzz_schools_caption_desc' => 'Details',
    '_modzzz_schools_subprofile_form_header_info' => 'Info',
    '_modzzz_schools_caption_browse_school_instructors' => 'Browse School Instructors',
  
	'_modzzz_schools_form_course_invalid_course' => 'Course Name entered is not an active site member',  
	'_modzzz_schools_block_browse_courses' => 'School Courses',
	'_modzzz_schools_page_title_courses_add' => 'Add a Course for School - {0}',
	'_modzzz_schools_page_title_courses_browse' => 'Browse Courses for School - {0}',  
    '_modzzz_schools_action_title_add_courses' => 'Add Course',
    '_modzzz_schools_page_title_courses_edit' => 'Edit School Course',
    '_modzzz_schools_msg_school_course_was_deleted' => 'School Course was successfully deleted',
    '_modzzz_schools_msg_pending_courses_approval' => 'this school course is pending approval, please wait until it will be activated',
    '_modzzz_schools_menu_view_courses' => 'Courses', 
    '_modzzz_schools_block_courses' => 'School Courses',
    '_modzzz_schools_form_caption_course_name' => 'Course Name', 
    '_modzzz_schools_privacy_view_courses' => 'All View Course to', 
    '_modzzz_schools_caption_desc' => 'Details',
    '_modzzz_schools_subprofile_form_header_info' => 'Info',
    '_modzzz_schools_caption_browse_school_courses' => 'Browse School Courses',
 
    '_modzzz_schools_wall_added_new_comment' => 'commented on a',
    '_modzzz_schools_wall_added_new_items' => 'added {0} new school(s)',
	'_modzzz_schools_single' => 'School',
    '_modzzz_schools_posted_in_topic' => 'Posted in Forum',
    '_modzzz_schools_posted_in_school' => 'Posted in School Listing', 
	'_modzzz_schools_message' => 'Message', 
    '_modzzz_schools_adm_stats' => 'Pending Schools',
 	'_sys_module_schools' => 'Schools',  

	'_modzzz_schools_block_youtubes' => 'Youtube Videos', 
	'_modzzz_schools_form_caption_youtube_link' => 'Video URL', 
	'_modzzz_schools_form_caption_youtube_caption' => 'Video Title',  
	'_modzzz_schools_form_header_youtube' => 'Youtube Videos',
	'_modzzz_schools_form_caption_youtube_attach' => 'Video',
	'_modzzz_schools_form_info_youtube_attach' => 'You can add multiple Youtube Videos',
	'_modzzz_schools_form_caption_youtube_choice' => 'Existing Videos',  
	'_modzzz_schools_form_info_youtube_choice' => 'Uncheck Videos that you want to remove',  
    '_modzzz_schools_page_title_embed_video' => 'Embed Video for - ',
    '_modzzz_schools_action_embed_video' => 'Embed Video',
    '_modzzz_schools_block_video_embed' => 'Youtube Videos',
    '_modzzz_schools_block_course_details' => 'Course Details',

    '_mma_schools_files_add' => 'schools files add',  
    '_mma_schools_photos_add' => 'schools photos add',  
    '_mma_schools_videos_add' => 'schools videos add',  
    '_mma_schools_sounds_add' => 'schools sounds add',  
    '_modzzz_schools_block_location' => 'Location',
    '_modzzz_schools_form_caption_president' => 'President',
    '_modzzz_schools_form_caption_motto' => 'Motto',
    '_modzzz_schools_form_caption_affiliations' => 'Affiliations',
    '_modzzz_schools_form_caption_mascot' => 'Mascot',
    '_modzzz_schools_form_caption_nickname' => 'Nickname',
    '_modzzz_schools_form_caption_colors' => 'Colors',
    '_modzzz_schools_block_map_view' => 'Map View',
    '_modzzz_schools_form_header_main_campus' => 'Main Campus',
    '_modzzz_schools_category' => 'Category',
    '_modzzz_schools_go' => 'Go',
	'_modzzz_schools_browse_schools_in_country' => 'Browse schools in {0}', 

    '_modzzz_schools_action_title_add_student' => 'Add Student',
 
	'_modzzz_schools_form_caption_enter_student' => 'Enter Student(s)', 
	'_modzzz_schools_form_info_enter_student' => 'You can enter multiple student names (separated by a comma)', 
	'_modzzz_schools_title_add_students' => 'Add Students to School',
 
    '_modzzz_schools_form_caption_credits' => 'Credits',
    '_modzzz_schools_form_caption_course_code' => 'Course Code',
    '_modzzz_schools_form_caption_instructors' => 'Instructors',
    '_modzzz_schools_form_caption_semester' => 'Semester',
    '_modzzz_schools_form_caption_timetable' => 'Timetable',
    '_modzzz_schools_form_caption_delivery_methods' => 'Delivery Methods',
    '_modzzz_schools_form_caption_overview' => 'Overview',
    '_modzzz_schools_form_caption_objectives' => 'Objectives (Learning Outcomes)',
    '_modzzz_schools_form_caption_prerequisite' => 'Prerequisites',
    '_modzzz_schools_form_caption_content' => 'Course Content',
    '_modzzz_schools_form_caption_assessment' => 'Assessment',
    '_modzzz_schools_form_caption_materials' => 'Course Materials',
    '_modzzz_schools_form_caption_specialization' => 'Specialization',
 
    '_modzzz_schools_page_caption_credits' => 'Credits',
    '_modzzz_schools_page_caption_course_code' => 'Course Code',
    '_modzzz_schools_page_caption_instructors' => 'Instructors',
    '_modzzz_schools_page_caption_semester' => 'Semester',
    '_modzzz_schools_page_caption_timetable' => 'Timetable',
    '_modzzz_schools_page_caption_delivery_methods' => 'Delivery Methods',
    '_modzzz_schools_page_caption_overview' => 'Overview',
    '_modzzz_schools_page_caption_objectives' => 'Objectives (Learning Outcomes)',
    '_modzzz_schools_page_caption_prerequisite' => 'Prerequisites',
    '_modzzz_schools_page_caption_content' => 'Course Content',
    '_modzzz_schools_page_caption_assessment' => 'Assessment',
    '_modzzz_schools_page_caption_materials' => 'Course Materials',
    '_modzzz_schools_page_caption_specialization' => 'Specialization',
 
    '_modzzz_schools_one' => 'One',
    '_modzzz_schools_two' => 'Two',
    '_modzzz_schools_three' => 'Three',
    '_modzzz_schools_four' => 'Four',
  
  
	'_modzzz_schools_form_event_invalid_event' => 'Event Name entered is not an active site member',  
	'_modzzz_schools_block_browse_events' => 'School Events',
	'_modzzz_schools_page_title_events_add' => 'Add a Event for School - {0}',
	'_modzzz_schools_page_title_events_browse' => 'Browse Events for School - {0}',  
    '_modzzz_schools_action_title_add_events' => 'Add Event',
    '_modzzz_schools_page_title_events_edit' => 'Edit School Event',
    '_modzzz_schools_msg_school_event_was_deleted' => 'School Event was successfully deleted',
    '_modzzz_schools_msg_pending_events_approval' => 'this school event is pending approval, please wait until it will be activated',
    '_modzzz_schools_menu_view_events' => 'Events', 
    '_modzzz_schools_block_events' => 'School Events',
    '_modzzz_schools_form_caption_event_name' => 'Event Name', 
    '_modzzz_schools_privacy_view_events' => 'All View Event to', 
    '_modzzz_schools_caption_desc' => 'Details',
    '_modzzz_schools_subprofile_form_header_info' => 'Info',
    '_modzzz_schools_caption_browse_school_events' => 'Browse School Events',
	'_modzzz_schools_event' => 'School Event',
 
	'_modzzz_schools_block_browse_news' => 'School News',
	'_modzzz_schools_page_title_news_add' => 'Add a News for School - {0}',
	'_modzzz_schools_page_title_news_browse' => 'Browse News for School - {0}',  
    '_modzzz_schools_action_title_add_news' => 'Add News',
    '_modzzz_schools_page_title_news_edit' => 'Edit School News',
    '_modzzz_schools_msg_school_news_was_deleted' => 'School News was successfully deleted',
    '_modzzz_schools_msg_pending_news_approval' => 'this school news is pending approval, please wait until it will be activated',
    '_modzzz_schools_menu_view_news' => 'News', 
    '_modzzz_schools_block_news' => 'School News',
    '_modzzz_schools_form_caption_news_name' => 'News Name', 
    '_modzzz_schools_privacy_view_news' => 'All View News to', 
    '_modzzz_schools_caption_desc' => 'Details',
    '_modzzz_schools_subprofile_form_header_info' => 'Info',
    '_modzzz_schools_caption_browse_school_news' => 'Browse School News',
 
	'_modzzz_schools_block_browse_student' => 'Students',
	'_modzzz_schools_page_title_student_add' => 'Add a Student for School - {0}',
	'_modzzz_schools_page_title_alumni_browse' => 'Browse Alumni for School - {0}',  
	'_modzzz_schools_page_title_student_browse' => 'Browse Students for School - {0}',  
    '_modzzz_schools_action_title_add_student' => 'Add Student',
    '_modzzz_schools_page_title_student_edit' => 'Edit Student',
    '_modzzz_schools_msg_school_student_was_deleted' => 'Student was successfully deleted',
    '_modzzz_schools_msg_pending_student_approval' => 'this student is pending approval, please wait until it will be activated', 
    '_modzzz_schools_menu_view_alumni' => 'Alumni',
	'_modzzz_schools_menu_view_student' => 'Students', 
    '_modzzz_schools_block_student' => 'Students',
    '_modzzz_schools_block_students' => 'Students',
    '_modzzz_schools_block_alumni' => 'Alumni',
    '_modzzz_schools_form_caption_student_name' => 'Student Name', 
    '_modzzz_schools_form_err_student_name' => 'You must enter Student Name',  
    '_modzzz_schools_privacy_view_student' => 'All View Student to', 
    '_modzzz_schools_form_caption_details' => 'Details',
    '_modzzz_schools_subprofile_form_header_info' => 'Info',
    '_modzzz_schools_caption_browse_school_student' => 'Browse Students',
    '_modzzz_schools_caption_browse_school_alumni' => 'Browse Alumni',
 
   '_modzzz_schools_event_join_success' => 'You have successfully joined this event',
   '_modzzz_schools_event_join_success_pending' => 'You have successfully joined this event, please wait while your request is reviewed by event admin(s)',
   '_modzzz_schools_event_joined_already' => 'You have already joined this event',
   '_modzzz_schools_event_joined_already_pending' => 'Your join request is pending approval.',
   '_modzzz_schools_event_leave_success' => 'You have successfully left this event',
   '_modzzz_schools_form_info_event_join_confirmation' => 'If enabled, event admin(s) will have to confirm each member before he/she is added as a participant.',

   '_modzzz_schools_privacy_view_participants' => 'View Participants',
   '_modzzz_schools_block_participants' => 'Participants',
   '_modzzz_schools_block_participants_unconfirmed' => 'Unconfirmed Participants',
   '_modzzz_schools_title_send_invitation' => 'Send Invitation',
   '_modzzz_schools_friend' => 'Friend',
   '_modzzz_schools_action_manage_event_fans' => 'Participants',
   '_modzzz_schools_caption_location_for_school' => 'Location for School',
   '_modzzz_schools_on' => 'on',
   '_modzzz_schools_form_caption_membership_type' => 'Membership Type',
   '_modzzz_schools_option_student' => 'Student',
   '_modzzz_schools_option_alumni' => 'Alumni',
 
   '_modzzz_schools_posted' => 'Posted',
   '_modzzz_schools_by' => 'by',
   '_modzzz_schools_form_caption_or' => '<b>OR</b>',
   '_modzzz_schools_form_caption_use_profile_desc' => 'Use Profile Description', 
   '_modzzz_schools_form_caption_use_profile_photo' => 'Use Profile Photo',
   '_modzzz_schools_form_label_yes' => 'Yes',
   '_modzzz_schools_msg_invalid_student' => 'Username entered is not an active member of the site',

   '_modzzz_schools_form_caption_student_type' => 'Student Type',
   '_modzzz_schools_form_caption_enter_nick' => 'If Site Member, enter NickName',
   '_modzzz_schools_form_info_enter_nick' => 'This must be a valid username of an existing active site member',
   '_modzzz_schools_form_caption_continue' => 'Continue', 
   '_modzzz_schools_option_internal' => 'Site Member',
   '_modzzz_schools_option_external' => 'Non-Member',

   '_modzzz_schools_msg_desc_none' => 'None available',
   '_modzzz_schools_option_no' => 'No',
   '_modzzz_schools_option_yes' => 'Yes',

   '_modzzz_schools_form_caption_year_entered' => 'Year Entered',
   '_modzzz_schools_form_err_year_entered' => 'You must enter Year Entered',
   '_modzzz_schools_form_caption_year_left' => 'Year Left',

   '_modzzz_schools_header_additional_iInfo' => 'Additional Info',
   '_modzzz_schools_label_students' => 'Students Checked-In',
   '_modzzz_schools_label_alumni' => 'Alumni Checked-In',
   '_modzzz_schools_label_fans' => 'Fans Checked-In',
   '_modzzz_schools_label_instructors' => 'Instructors',
   '_modzzz_schools_label_courses' => 'Courses',
   '_modzzz_schools_label_events' => 'Events',
   '_modzzz_schools_label_news' => 'News',

   '_modzzz_schools_form_caption_enrolled_students' => 'Enrolled Students',
   '_mma_schools_add_student' => 'schools add student',
   '_modzzz_schools_caption_event_for_school' => 'Event for School',
  
   '_mma_schools_add_instructor' => 'schools add instructor',
   '_modzzz_schools_block_instructors' => 'Instructors',
   '_modzzz_schools_msg_invalid_instructor' => 'Username entered is not an active member of the site',
   '_modzzz_schools_form_caption_instructor_type' => 'Instructor Type',
   '_modzzz_schools_action_title_i_am_instructor' => 'I\'m a Instructor',
   '_mma_schools_allow_embed' => 'schools allow embed',
   '_modzzz_schools_calendar' => 'Calendar - ',


 
);